import { useState } from "react";

import type { Answer, EvidenceBase } from "../types";

interface Props {
  question: string;
  answer: Answer;
  evidence: EvidenceBase;
}

function markdown({ question, answer, evidence }: Props): string {
  const sources = evidence.webSources.length
    ? evidence.webSources.map((source) => `- [${source.title}](${source.url})`).join("\n")
    : answer.sources.map((source) => `- [${source.title}](${source.url})`).join("\n");

  return [
    `# ${answer.title}`,
    "",
    `Question: ${question}`,
    "",
    answer.summary,
    "",
    "## Model shortlist",
    ...evidence.candidates.map(
      (candidate) =>
        `- ${candidate.player} (${candidate.club ?? "club unknown"}) — ${candidate.models_retrieved}/3 models, similarity ${candidate.mean_similarity.toFixed(2)}`,
    ),
    "",
    "## Statistical evidence",
    ...(answer.statistical_evidence.length ? answer.statistical_evidence : ["No statistical evidence recorded."]),
    "",
    "## Tactical evidence",
    ...(answer.tactical_evidence.length ? answer.tactical_evidence : ["No tactical evidence recorded."]),
    "",
    "## Limitations",
    ...(answer.limitations.length ? answer.limitations : ["None recorded."]),
    "",
    "## Sources",
    sources || "No web sources recorded.",
    "",
    `Generated by Halfspace ScoutLab. Evidence calls: ${evidence.toolCalls}.`,
  ].join("\n");
}

export function ScoutBriefActions(props: Props) {
  const [copied, setCopied] = useState(false);

  function download() {
    const blob = new Blob([markdown(props)], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${props.answer.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.md`;
    link.click();
    URL.revokeObjectURL(url);
  }

  async function copy() {
    await navigator.clipboard?.writeText(markdown(props));
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  }

  return (
    <div className="brief-actions" aria-label="Scout brief actions">
      <div>
        <span className="section__eyebrow">Take it out of the chat</span>
        <strong>Save this as a scouting brief</strong>
      </div>
      <div className="brief-actions__buttons">
        <button className="button button--ghost button--sm" type="button" onClick={copy}>
          {copied ? "Copied" : "Copy brief"}
        </button>
        <button className="button button--accent button--sm" type="button" onClick={download}>
          Download .md
        </button>
      </div>
    </div>
  );
}
